
project_id = "wutyryaqlmgsbllnyoop"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://wutyryaqlmgsbllnyoop.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_captcha_enabled = false
security_captcha_provider = "hcaptcha"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[functions.send-payment-reminder]
verify_jwt = false

[functions.daily-payment-check]
verify_jwt = false

[functions.domain-check]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.invite-client]
verify_jwt = true

[functions.confirm-invited-user]
verify_jwt = true

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
